# Storage Class for PostgreSQL 9.6

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-9.6-storage-class
  labels:
    app: postgres-9.6
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

# Persistence Volume for PostgreSQL 9.6
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-9.6-pv
  labels:
    app: postgres-9.6
spec:
  capacity:
    storage: 2Gi
  mountOptions:
    - hard
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-9.6-storage-class
  local:
    path: /run/desktop/mnt/host/c/Data/Postgres/9.6/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

