# Storage Class for PostgreSQL 9.6

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-9.6-storage-class
  labels:
    app: study
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

# Persistence Volume for PostgreSQL 9.6
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-9.6-pv
  labels:
    app: study
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-9.6-storage-class
  local:
    path: "C:\\Data\\Postgres\\9.6"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

---

# Persistence Volume Claim for PostgreSQL 9.6
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-9.6-pvc
  labels:
    app: study
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-9.6-storage-class
  resources:
    requests:
      storage: 1Gi

---

# Deployment for PostgreSQL 9.6
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-9.6-deployment
  labels:
    app: study
spec:
  selector:
    matchLabels:
      app: study

  template:
    metadata:
      labels:
        app: study
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.18-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: abc123
          ports:
            - containerPort: 5432
              name: postgres-9-6
          volumeMounts:
            - name: postgres-9-6
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-9-6
          persistentVolumeClaim:
            claimName: postgres-9.6-pvc

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-9-6-service
#   labels:
#     app: study
# spec:
#   ports:
#     - port: 5432
#   selector:
#     app: study
#     tier: postgres-9-6