# Persistence Volume Claim for PostgreSQL 9.6
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-9.6-pvc
  labels:
    app: postgres-9.6
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-9.6-storage-class
  resources:
    requests:
      storage: 1Gi

---

# Deployment for PostgreSQL 9.6
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-9.6-deployment
  labels:
    app: postgres-9.6
spec:
  selector:
    matchLabels:
      app: postgres-9.6

  template:
    metadata:
      labels:
        app: postgres-9.6
    spec:
      containers:
        - image: postgres:9.6.18-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: abc123
          ports:
            - containerPort: 5432
              name: postgres-9-6
          volumeMounts:
            - name: postgres-9-6-pod-volume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: postgres-9-6-pod-volume
          persistentVolumeClaim:
            claimName: postgres-9.6-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-9-6-service
  labels:
    app: postgres-9.6
spec:
  ports:
    - port: 5432
      targetPort: 5432 
  selector:
    app: postgres-9.6